apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: invoice-billing
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - cluster-issuer.yaml
  - hpa.yaml
  - servicemonitor.yaml
commonLabels:
  app: ai-invoice-billing
images:
  - name: ai-invoice-billing-backend
    newName: ai-invoice-billing-backend
    newTag: latest
  - name: ai-invoice-billing-frontend
    newName: ai-invoice-billing-frontend
    newTag: latest
